### PR TITLE
Revert "UI design"

### PR DESCRIPTION
**Pull request by AdornChoga**
In this pull request, I added CSS styles to the UI of the website.

### CODE REVIEW

**Review by mikethreels — CHANGES_REQUESTED** [review]
Hi Adorn, 

Good job keeping the stylesheets clean 👍 
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] your styling doesn't match the template, please make sure your project looks exactly the same as in the template below I've added a screenshot.
Screenshot 2022-02-24 132511

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by AdornChoga** [comment]
Hello @mikethreels 
Thank you for your feedback. Could you please elaborate and specify which parts of the design I did not follow. In as much as the colors and dimensions are concerned I seem to have followed the template guidelines.

**Comment by mikethreels** [comment]
Hi Adorn,
I don't have access to my computer at the moment, however as far as I remember the font wasn't matching and the completion status looks different. Make sure it looks like the template as much as possible. I will not have access to my computer for the rest of the day, if you don't agree with my review I advise you to request a second opinion so a senior code reviewer will have a look at your project.

Sorry I'm not able to help you any more, I hope this helps.

**Comment by AdornChoga** [comment]
Thank you @mikethreels. You are right, I did not use the exact fonts in the template and my color for the status bar is a little darker as well. Pardon me, I did not know that even the fonts are required to be exactly similar. I will get down to fixing that right away.
Thank you for your clarification.

**Review by er-contreras — APPROVED** [review]
Hi @AdornChoga , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

- Well done!

Felix

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
